sudo: required
services:
    - docker

before_install:
    - docker build -t dasrajendra2004/multi-docker-ci -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dasrajendra2004/multi-docker-ci npm test

after_success:
    - docker build -t dasrajendra2004/multi-client ./client
    - docker build -t dasrajendra2004/multi-nginx ./nginx
    - docker build -t dasrajendra2004/multi-server ./server
    - docker build -t dasrajendra2004/multi-worker ./worker
    #Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Push images to docker hub
    - docker push dasrajendra2004/multi-client
    - docker push dasrajendra2004/multi-nginx
    - docker push dasrajendra2004/multi-server
    - docker push dasrajendra2004/multi-worker